name: Release

on: workflow_dispatch

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Git credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}
      - name: Git Username
        run: git config --global user.name "Michael Krolikowski"
      - name: Git E-Mail
        run: git config --global user.email "mkroli@yahoo.de"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import PGP Key
        run: echo "${PGP_KEY}" | gpg --import --batch
        env:
          PGP_KEY: ${{ secrets.PGP_KEY }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_KEY_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: sbt -Dsbt.color=true -Dsbt.supershell=false "release with-defaults"
